set(_CATKIN_CURRENT_PACKAGE "display")
set(display_VERSION "0.0.0")
set(display_MAINTAINER "abhishek <abhishek@todo.todo>")
set(display_PACKAGE_FORMAT "1")
set(display_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(display_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(display_BUILDTOOL_DEPENDS "catkin")
set(display_BUILDTOOL_EXPORT_DEPENDS )
set(display_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(display_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(display_TEST_DEPENDS )
set(display_DOC_DEPENDS )
set(display_DEPRECATED "")